version: '3.9'

services:
  nginx:
    container_name: nginx
    restart: on-failure
    image: jonasal/nginx-certbot:latest
    environment:
      - CERTBOT_EMAIL=YOUR_MAIL
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - ELLIPTIC_CURVE=secp256r1
      - USE_ECDSA=0
      - RENEWAL_INTERVAL=8d
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - nginx.conf:/etc/nginx
      - static_volume:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-api
      - sendhooks
      - sendhooks-monitoring

  redis:
    image: redis:latest
    hostname: redis
    restart: always
    ports:
      - "6379:6379" # Exposes Redis on localhost via port 6379

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./mongo:/data/db

  sendhooks:
    image: transfa/sendhooks
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - ./config.json:/root/config.json # Mounts config.json from host to container

  flask-api:
    build: ./api/
    container_name: flask_api
    restart: on-failure
    ports:
      - "5001:5000" # Exposes Flask API on localhost via port 5001, internal port 5000
    depends_on:
      - sendhooks

  sendhooks-monitoring:
    image: transfa/sendhooks-monitoring
    container_name: sendhooks_monitoring
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - "5002:5002"
      - "3000:3000"
    depends_on:
      - sendhooks
      - mongo
      - redis
